### PR TITLE
Support for LSF scheduler and Mainz GPU config

### PR DESCRIPTION
**Pull request by thehrh**

### CODE REVIEW

**Comment by briedel** [comment]
L332 and L335 in `submit.py ` should use `self.config` not  `submit_conf`

**Comment by thehrh** [comment]
Are you suggesting to set these two parameters somewhere else than under the `SubmitFile` entry, or that I remove the assignment `submit_conf = self.config['SubmitFile']`?

**Comment by dsschult** [comment]
Is there a reason why the memory needs to be scaled?

**Comment by thehrh** [comment]
The memory needs to be given in kB over here.

**Comment by dsschult** [comment]
Ah.  That would be good to add in the comments.

**Comment by thehrh** [comment]
Come to think about it, I see no reason why this would be a problem specific to LSF (?). Would it make sense to implement a function for the submit base class that will scale the requested memory for every derived class when this parameter is configured?

**Comment by thehrh** [comment]
In general, we probably want to prevent people from implementing config parameters with the same functionality but different names across the various submit classes, right?

**Comment by briedel** [comment]
Does the LSF not have units? PBS usually allows one to define units of some sort, i.e. `#PBS -l pmem=2700mb`

**Comment by thehrh** [comment]
If there is a way, I haven't found it. As far as I know, the user is dependent on the way the cluster has been configured.

**Comment by dsschult** [comment]
If all LSF versions measure in KB, I'd be inclined to hard-code the scaling factor instead of leaving it up to the user.  The user will eventually forget to set it and bad things will happen.

**Comment by briedel** [comment]
Reading a `bsub` man page (http://www.vub.ac.be/BFUCC/LSF/bsub.1.html). This appears to be the case. One could still make the scaling factor an option. It should scale the memory safety margin rather than the difference between kB and MB.

**Comment by thehrh** [comment]
Please take a look at the changes I made above and let me know if this is along the lines of what you had in mind. Note the additional modification of the advertised memory for GPU-Glideins with PBS when the requested memory exceeds the per-core limit: it seemed like it should also match the per-core limit in that case (?).

**Comment by thehrh** [comment]
This last change allows overriding LSF memory unit defaults in the config.

**Pull request merged**
